"""Emit the frontend scene-script preview contract from the Python schema.

The web preview used to keep its own list of prop/environment kinds in a
``switch`` with a grey-box ``default``. That list drifted: 7 of the 25 kinds the
schema declares had geometry, and the other 18 rendered as the same default
``#888888`` box Blender uses for an unimplemented asset -- so the browser could
not tell a faithful preview from a missing one either.

Both halves of the same contract now derive from one place: the enums come from
``PropType``/``EnvironmentType`` and the colours from the converter's palette, so
a new kind cannot ship on the backend without the frontend's completeness test
failing rather than silently falling back to a grey box.

The file also carries the director motion preset ids (from
``scene3d/director_motion.py``): the workbench preset tables must match what the
/director-motion endpoint actually expands, or a shown-but-unknown preset fails
at the gate and a backend-only preset is a capability the user never sees.

Run via ``python -m app.cli.generate_scene_script_preview_contract``; a test
asserts the checked-in file matches this generator byte for byte.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import get_args

from app.schemas.scene_script import EnvironmentType, PropType
from app.services.scene3d.blender_converter import (
    _ASSET_COLORS,
    _DEGRADED_ASSET_COLOR,
    _PART_COLOR_OVERRIDES,
)
from app.services.scene3d.director_motion import (
    CAMERA_MOTION_PRESET_IDS,
    CHARACTER_MOTION_PRESET_IDS,
)

# Resolved from this file rather than the process CWD so the CLI can be run from
# anywhere in the monorepo and still write to the same checked-in path.
# This file is <repo>/apps/api/app/cli/<name>.py, so parents[4] is <repo>.
_REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_OUTPUT = _REPO_ROOT / "apps" / "web" / "src" / "types" / "scene-script.generated.ts"


def render_typescript() -> str:
    """Return the TypeScript module text for the scene-script preview contract."""

    prop_types = list(get_args(PropType))
    environment_types = list(get_args(EnvironmentType))
    lines = [
        "/*",
        " * Generated by app.cli.generate_scene_script_preview_contract.",
        " * Do not edit manually -- run",
        " *   python -m app.cli.generate_scene_script_preview_contract",
        " * Source of truth: app/schemas/scene_script.py + scene3d/blender_converter.py"
        " + scene3d/director_motion.py",
        " *",
        " * apps/web tests that every preview kind has geometry import these, so a",
        " * kind added to the schema fails the frontend build instead of silently",
        " * rendering as a grey placeholder box.",
        " */",
        "",
        "// Kinds the backend schema declares, so the preview can assert it covers all of them.",
        f"export const PROP_TYPES = [{', '.join(_quoted(t) for t in prop_types)}] as const;",
        "",
        f"export const ENVIRONMENT_TYPES = [{', '.join(_quoted(t) for t in environment_types)}] as const;",
        "",
        "export type PropTypeName = (typeof PROP_TYPES)[number];",
        "export type EnvironmentTypeName = (typeof ENVIRONMENT_TYPES)[number];",
        "",
        "/**",
        " * Colour each declared kind renders in. Mirrors the converter's",
        " * ``_ASSET_COLORS`` so the browser preview and the Blender frames agree,",
        " * and so the placeholder below is the one colour no real asset uses.",
        " */",
        "export const SCENE_SCRIPT_ASSET_COLORS: Readonly<Record<string, string>> = {",
    ]
    for asset_type in sorted(set(prop_types) | set(environment_types)):
        # The palette is keyed by the converter's own asset names, which are the
        # schema's enum members plus ``lowpoly_human``.
        color = _ASSET_COLORS.get(asset_type, "#B08D57")
        lines.append(f"  {asset_type}: {_quoted(color)},")
    lines.extend(
        [
            "};",
            "",
            "/**",
            " * Per-part overrides for multi-part assets, keyed by the part-name",
            " * suffix the converter's builders assign. Without this a tree renders",
            " * as one brown mass instead of a trunk under a canopy, so the browser",
            " * would disagree with the Blender frames about what a tree is.",
            " */",
            "export const SCENE_SCRIPT_PART_COLOR_OVERRIDES: Readonly<",
            "Record<string, string>",
            "> = {",
        ],
    )
    for suffix in sorted(_PART_COLOR_OVERRIDES):
        lines.append(f"  {_quoted(suffix)}: {_quoted(_PART_COLOR_OVERRIDES[suffix])},")
    lines.extend(
        [
            "};",
            "",
            "/**",
            " * The colour a kind with no geometry renders in, chosen so it can never be",
            " * mistaken for a real surface. Must equal the converter's",
            f" * ``_DEGRADED_ASSET_COLOR`` ({_DEGRADED_ASSET_COLOR}).",
            " */",
            f"export const PLACEHOLDER_ASSET_COLOR = {_quoted(_DEGRADED_ASSET_COLOR)};",
            "",
        ],
    )
    lines.extend(
        [
            "// Motion preset ids the backend /director-motion endpoint expands (from",
            "// scene3d/director_motion.py), sorted for a deterministic diff. The",
            "// workbench preset tables must match these exactly: a preset the UI",
            "// shows but the backend lacks fails at the gate, and one only the",
            "// backend has is a capability the user never sees.",
            f"export const DIRECTOR_CAMERA_MOTION_PRESET_IDS = [{', '.join(_quoted(preset) for preset in sorted(CAMERA_MOTION_PRESET_IDS))}] as const;",
            "",
            f"export const DIRECTOR_CHARACTER_MOTION_PRESET_IDS = [{', '.join(_quoted(preset) for preset in sorted(CHARACTER_MOTION_PRESET_IDS))}] as const;",
            "",
        ],
    )
    return "\n".join(lines)


def _quoted(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(render_typescript(), encoding="utf-8")
    print(f"wrote {arguments.output}")


if __name__ == "__main__":
    main()
