"""Emit the frontend scene-script preview contract from the Python schema.

The web preview used to keep its own list of prop/environment kinds in a
``switch`` with a grey-box ``default``. That list drifted: 7 of the 25 kinds the
schema declares had geometry, and the other 18 rendered as the same default
``#888888`` box Blender uses for an unimplemented asset -- so the browser could
not tell a faithful preview from a missing one either.

Both halves of the same contract now derive from one place: the enums come from
``PropType``/``EnvironmentType`` and the colours from the converter's palette, so
a new kind cannot ship on the backend without the frontend's completeness test
failing rather than silently falling back to a grey box.

The file also carries the director motion preset ids (from
``scene3d/director_motion.py``): the workbench preset tables must match what the
/director-motion endpoint actually expands, or a shown-but-unknown preset fails
at the gate and a backend-only preset is a capability the user never sees.

Run via ``python -m app.cli.generate_scene_script_preview_contract``; a test
asserts the checked-in file matches this generator byte for byte.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import get_args

from app.schemas.scene_script import EnvironmentType, PropType
from app.services.scene3d import asset_dimensions
from app.services.scene3d.blender_converter import (
    _ASSET_COLORS,
    _DEGRADED_ASSET_COLOR,
    _PART_COLOR_OVERRIDES,
)
from app.services.scene3d import character_pose, held_item_grip, object_motion
from app.services.scene3d.director_motion import (
    CAMERA_MOTION_PRESET_IDS,
    CHARACTER_MOTION_PRESET_IDS,
)
from app.services.scene3d.rotation_pivot import KIND_ROTATION_PIVOT

# Resolved from this file rather than the process CWD so the CLI can be run from
# anywhere in the monorepo and still write to the same checked-in path.
# This file is <repo>/apps/api/app/cli/<name>.py, so parents[4] is <repo>.
_REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_OUTPUT = _REPO_ROOT / "apps" / "web" / "src" / "types" / "scene-script.generated.ts"


def render_typescript() -> str:
    """Return the TypeScript module text for the scene-script preview contract."""

    prop_types = list(get_args(PropType))
    environment_types = list(get_args(EnvironmentType))
    lines = [
        "/*",
        " * Generated by app.cli.generate_scene_script_preview_contract.",
        " * Do not edit manually -- run",
        " *   python -m app.cli.generate_scene_script_preview_contract",
        " * Source of truth: app/schemas/scene_script.py + scene3d/blender_converter.py"
        " + scene3d/director_motion.py",
        " *",
        " * apps/web tests that every preview kind has geometry import these, so a",
        " * kind added to the schema fails the frontend build instead of silently",
        " * rendering as a grey placeholder box.",
        " */",
        "",
        "// Kinds the backend schema declares, so the preview can assert it covers all of them.",
        f"export const PROP_TYPES = [{', '.join(_quoted(t) for t in prop_types)}] as const;",
        "",
        f"export const ENVIRONMENT_TYPES = [{', '.join(_quoted(t) for t in environment_types)}] as const;",
        "",
        "export type PropTypeName = (typeof PROP_TYPES)[number];",
        "export type EnvironmentTypeName = (typeof ENVIRONMENT_TYPES)[number];",
        "",
        "/**",
        " * Colour each declared kind renders in. Mirrors the converter's",
        " * ``_ASSET_COLORS`` so the browser preview and the Blender frames agree,",
        " * and so the placeholder below is the one colour no real asset uses.",
        " */",
        "export const SCENE_SCRIPT_ASSET_COLORS: Readonly<Record<string, string>> = {",
    ]
    for asset_type in sorted(set(prop_types) | set(environment_types)):
        # The palette is keyed by the converter's own asset names, which are the
        # schema's enum members plus ``lowpoly_human``.
        color = _ASSET_COLORS.get(asset_type, "#B08D57")
        lines.append(f"  {asset_type}: {_quoted(color)},")
    lines.extend(
        [
            "};",
            "",
            "/**",
            " * Per-part overrides for multi-part assets, keyed by the part-name",
            " * suffix the converter's builders assign. Without this a tree renders",
            " * as one brown mass instead of a trunk under a canopy, so the browser",
            " * would disagree with the Blender frames about what a tree is.",
            " */",
            "export const SCENE_SCRIPT_PART_COLOR_OVERRIDES: Readonly<",
            "Record<string, string>",
            "> = {",
        ],
    )
    for suffix in sorted(_PART_COLOR_OVERRIDES):
        lines.append(f"  {_quoted(suffix)}: {_quoted(_PART_COLOR_OVERRIDES[suffix])},")
    lines.extend(
        [
            "};",
            "",
            "/**",
            " * Where a pitch/roll keyframe turns each kind, in Scene coords (Z-up),",
            " * scaled by `scale`. Generated from scene3d/rotation_pivot.py.",
            " *",
            " * NOT the authored `position`: that is where the object sits on the floor,",
            " * which for most kinds is its base. Turning about the base sweeps the whole",
            " * object around its own footprint instead of turning it on itself -- a crate",
            " * rotating 360 deg drifted 123 px of silhouette travel, against 8 px here.",
            " *",
            " * It is per-kind rather than a computed centroid because the right answer",
            " * differs per object: a tree sways about its root, a door about its hinge,",
            " * a rotor about its hub. Kinds are absent when the base IS the pivot.",
            " */",
            "export const KIND_ROTATION_PIVOT: Readonly<",
            "Partial<Record<PropTypeName | EnvironmentTypeName, readonly [number, number, number]>>",
            "> = {",
        ],
    )
    for kind, (px, py, pz) in sorted(KIND_ROTATION_PIVOT.items()):
        lines.append(f"  {_quoted(kind)}: [{px}, {py}, {pz}] as const,")
    lines.extend(
        [
            "};",
            "",
            "/**",
            " * Pose constants, from scene3d/character_pose.py -- the same numbers the",
            " * Blender converter uses. The walk curve is implemented once per language",
            " * (the runtimes share nothing), so these are the part that must not drift;",
            " * `test_character_pose_matches_preview` compares the two implementations'",
            " * actual output phase by phase, which catches the formulas too.",
            " *",
            " * Stride is proportional to the leg, so `stride / (4L)` -- and therefore the",
            " * leg angle -- is the same for every figure: a child takes shorter steps",
            " * rather than swinging harder.",
            " */",
            "export const POSE_CONSTANTS = {",
            f"  walkStrideMetres: {character_pose.WALK_STRIDE_METRES},",
            f"  referenceLegLengthMetres: {character_pose.REFERENCE_LEG_LENGTH_METRES},",
            f"  stanceFraction: {character_pose.STANCE_FRACTION},",
            f"  walkMaxLegRadians: {character_pose.WALK_MAX_LEG_RADIANS},",
            f"  defaultLegLengthMetres: {character_pose.DEFAULT_LEG_LENGTH_METRES},",
            f"  walkArmOverLeg: {character_pose.WALK_ARM_OVER_LEG},",
            f"  walkTorsoRadians: {character_pose.WALK_TORSO_RADIANS},",
            f"  gestureHeadTiltRadians: {character_pose.GESTURE_HEAD_TILT_RADIANS},",
            f"  standLegSpreadRadians: {character_pose.STAND_LEG_SPREAD_RADIANS},",
            f"  standArmRestRadians: {character_pose.STAND_ARM_REST_RADIANS},",
            f"  gestureArmRaiseRadians: {character_pose.GESTURE_ARM_RAISE_RADIANS},",
            f"  gestureArmOutRadians: {character_pose.GESTURE_ARM_OUT_RADIANS},",
            f"  gestureTorsoRadians: {character_pose.GESTURE_TORSO_RADIANS},",
            f"  gestureHeadRadians: {character_pose.GESTURE_HEAD_RADIANS},",
            f"  sitThighLiftRadians: {character_pose.SIT_THIGH_LIFT_RADIANS},",
            f"  sitTorsoRadians: {character_pose.SIT_TORSO_RADIANS},",
            f"  sitHeadRadians: {character_pose.SIT_HEAD_RADIANS},",
            f"  talkArmRadians: {character_pose.TALK_ARM_RADIANS},",
            f"  talkTorsoRadians: {character_pose.TALK_TORSO_RADIANS},",
            f"  talkMouthRatio: {character_pose.TALK_MOUTH_RATIO},",
            f"  mouthClosedRatio: {character_pose.MOUTH_CLOSED_RATIO},",
            "} as const;",
            "",
            "/**",
            " * Held-item grip geometry, from scene3d/held_item_grip.py.",
            " *",
            " * A character holding something used to get a prop at a hand offset that",
            " * was a fixed 0.32 m and 0.72 of the character's height, while the rig hangs",
            " * the hand at 0.49 of it and places the arm lateral in proportion to height.",
            " * The two matched at exactly 1.75 m and disagreed for everyone else: a 1.1 m",
            " * character's weapon sat 60% further outboard than their hand.",
            " *",
            " * `armPitchRadians` is the forward rotation the arms need to bring the hand",
            " * up to the grip. It is height-independent because the shoulder and the target",
            " * are both proportional to height.",
            " */",
            "export const HOLD_GRIP = {",
            f"  armPitchRadians: {held_item_grip.hold_arm_pitch():.6f},",
            f"  gripHeightRatio: {held_item_grip.GRIP_HEIGHT_RATIO},",
                        "  kindGripRatio: {"
            + ", ".join(
                f"{_quoted(kind)}: {ratio}" for kind, ratio in sorted(held_item_grip.KIND_GRIP_RATIO.items())
            )
            + "},",
            "} as const;",
            "",
            "/**",
            " * The rig's proportions, from scene3d/held_item_grip.py. The held-item",
            " * geometry above is derived from these, so a change to the rig has to move",
            " * them together -- which is what a fixed metre constant cannot do.",
            " */",
            "export const CHARACTER_RIG_FRACTIONS_MIRROR = {",
            f"  leg: {held_item_grip.RIG_FRACTIONS['leg']},",
            f"  torso: {held_item_grip.RIG_FRACTIONS['torso']},",
            f"  neck: {held_item_grip.RIG_FRACTIONS['neck']},",
            f"  headRadius: {held_item_grip.RIG_FRACTIONS['head_radius']},",
            f"  arm: {held_item_grip.RIG_FRACTIONS['arm']},",
            f"  armHang: {held_item_grip.RIG_FRACTIONS['arm_hang']},",
            f"  limbWidth: {held_item_grip.RIG_FRACTIONS['limb_width']},",
            f"  torsoWidth: {held_item_grip.RIG_FRACTIONS['torso_width']},",
            f"  torsoDepth: {held_item_grip.RIG_FRACTIONS['torso_depth']},",
            f"  legSpread: {held_item_grip.RIG_FRACTIONS['leg_spread']},",
            f"  armOutset: {held_item_grip.RIG_FRACTIONS['arm_outset']},",
            f"  armWidthFactor: {held_item_grip.RIG_FRACTIONS['arm_width_factor']},",
            f"  legDepthFactor: {held_item_grip.RIG_FRACTIONS['leg_depth_factor']},",
            f"  headSeat: {held_item_grip.RIG_FRACTIONS['head_seat']},",
            "} as const;",
            "",
            "/**",
            " * Non-human motion constants, from scene3d/object_motion.py. A door, a wheel",
            " * and a dropship have no body, so their motion is a delta on the rest pose",
            " * rather than a set of joint angles -- see objectMotion.ts.",
            " *",
            " * These are wall-clock cycles, not distance-driven: a door opens once across",
            " * its shot and a wheel turns whether or not it is moving.",
            " */",
            "export const OBJECT_MOTION_CONSTANTS = {",
            f"  driveStrideMetres: {object_motion.MOTION_STRIDE_METRES['drive']},",
            f"  flyoverStrideMetres: {object_motion.MOTION_STRIDE_METRES['flyover']},",
            f"  doorSwingSeconds: {object_motion.DOOR_SWING_SECONDS},",
            f"  continuousCycleSeconds: {object_motion.CONTINUOUS_CYCLE_SECONDS},",
            f"  doorSwingOpenRadians: {object_motion.DOOR_SWING_OPEN_RADIANS},",
            "} as const;",
            "",
            "/**",
            " * The colour a kind with no geometry renders in, chosen so it can never be",
            " * mistaken for a real surface. Must equal the converter's",
            f" * ``_DEGRADED_ASSET_COLOR`` ({_DEGRADED_ASSET_COLOR}).",
            " */",
            f"export const PLACEHOLDER_ASSET_COLOR = {_quoted(_DEGRADED_ASSET_COLOR)};",
            "",
        ],
    )
    lines.extend(
        [
            "// Motion preset ids the backend /director-motion endpoint expands (from",
            "// scene3d/director_motion.py), sorted for a deterministic diff. The",
            "// workbench preset tables must match these exactly: a preset the UI",
            "// shows but the backend lacks fails at the gate, and one only the",
            "// backend has is a capability the user never sees.",
            f"export const DIRECTOR_CAMERA_MOTION_PRESET_IDS = [{', '.join(_quoted(preset) for preset in sorted(CAMERA_MOTION_PRESET_IDS))}] as const;",
            "",
f"export const DIRECTOR_CHARACTER_MOTION_PRESET_IDS = [{', '.join(_quoted(preset) for preset in sorted(CHARACTER_MOTION_PRESET_IDS))}] as const;",
            "",
        ]
    )
    # Sizes, for the same reason the colours are here: the SceneScript generator
    # writes `scale` blind unless something tells it what a scale of 1 measures,
    # and a `pillar` at 4.5 is a 19 m column beside a 1.75 m person. The values
    # are mirrored from `sceneScriptGeometry.tsx` and held to it by
    # `sceneScriptGeometry.dimensions.test.ts`, which measures the real geometry
    # rather than trusting this table.
    lines.extend(
        [
            "/**",
            " * What each kind measures in metres at `scale = 1`, SceneScript space (Z-up).",
            " *",
            " * Mirrored from `apps/web/.../sceneScriptGeometry.tsx` and checked against it",
            " * by measuring the rendered bounding box. `base` is how far the geometry's",
            " * underside floats above z = 0 — a non-zero `base` means anything authored",
            " * on the ground is underneath the object, not beside it.",
            " */",
            "export interface AssetSceneDimensions {",
            "  /** Extent along x (right), metres. */",
            "  width: number;",
            "  /** Extent along z (up), metres. */",
            "  height: number;",
            "  /** Extent along y (forward), metres. */",
            "  depth: number;",
            "  /** Height of the underside above the ground, metres. */",
            "  base: number;",
            "  shape: string;",
            "  note: string;",
            "}",
            "",
            "export const ASSET_SCENE_DIMENSIONS: Record<string, AssetSceneDimensions> = {",
        ]
    )
    for kind in asset_dimensions.kinds():
        dims = asset_dimensions.rendered(kind, 1.0)
        assert dims is not None
        lines.append(
            f"  {kind}: {{ width: {_number(dims.width)}, height: {_number(dims.height)}, "
            f"depth: {_number(dims.depth)}, base: {_number(dims.base)}, "
            f"shape: {_quoted(dims.shape)}, note: {_quoted(dims.note)} }},"
        )
    lines.extend(
        [
            "};",
            "",
            "/** The size a SceneScript is implicitly written against, in metres. */",
            f"export const REFERENCE_PERSON_HEIGHT = {_number(asset_dimensions.REFERENCE_PERSON_HEIGHT)};",
            "",
        ]
    )
    return "\n".join(lines)


def _number(value: float) -> str:
    """A JS number literal that keeps a trailing `.0` off the output."""
    return str(int(value)) if float(value).is_integer() else str(value)


def _quoted(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(render_typescript(), encoding="utf-8")
    print(f"wrote {arguments.output}")


if __name__ == "__main__":
    main()
