/*
 * Generated by app.cli.generate_scene_script_preview_contract.
 * Do not edit manually -- run
 *   python -m app.cli.generate_scene_script_preview_contract
 * Source of truth: app/schemas/scene_script.py + scene3d/blender_converter.py + scene3d/director_motion.py
 *
 * apps/web tests that every preview kind has geometry import these, so a
 * kind added to the schema fails the frontend build instead of silently
 * rendering as a grey placeholder box.
 */

// Kinds the backend schema declares, so the preview can assert it covers all of them.
export const PROP_TYPES = ["round_table", "rect_table", "chair", "stool", "lantern", "box", "crate", "vase", "weapon", "scroll", "book", "cup"] as const;

export const ENVIRONMENT_TYPES = ["wall", "pillar", "floor", "gable_roof", "flat_roof", "door", "window", "stairs", "platform", "tree", "rock", "fence", "ground"] as const;

export type PropTypeName = (typeof PROP_TYPES)[number];
export type EnvironmentTypeName = (typeof ENVIRONMENT_TYPES)[number];

/**
 * Colour each declared kind renders in. Mirrors the converter's
 * ``_ASSET_COLORS`` so the browser preview and the Blender frames agree,
 * and so the placeholder below is the one colour no real asset uses.
 */
export const SCENE_SCRIPT_ASSET_COLORS: Readonly<Record<string, string>> = {
  book: "#8B3A3A",
  box: "#B08D57",
  chair: "#7A5230",
  crate: "#8C6239",
  cup: "#D9D8D0",
  door: "#5C3A21",
  fence: "#7E6242",
  flat_roof: "#5A5A62",
  floor: "#7A6748",
  gable_roof: "#8C4A38",
  ground: "#6E7A45",
  lantern: "#E8B84B",
  pillar: "#C4B79B",
  platform: "#8A7554",
  rect_table: "#A9743F",
  rock: "#82807A",
  round_table: "#8B5A2B",
  scroll: "#E8DCC0",
  stairs: "#96795A",
  stool: "#9C6B3F",
  tree: "#6B4A2A",
  vase: "#C86B8A",
  wall: "#CDBFA3",
  weapon: "#9AA3AD",
  window: "#A8CBD8",
};

/**
 * Per-part overrides for multi-part assets, keyed by the part-name
 * suffix the converter's builders assign. Without this a tree renders
 * as one brown mass instead of a trunk under a canopy, so the browser
 * would disagree with the Blender frames about what a tree is.
 */
export const SCENE_SCRIPT_PART_COLOR_OVERRIDES: Readonly<
Record<string, string>
> = {
  "_Blade": "#9AA3AD",
  "_Canopy": "#4E7A3A",
  "_Grip": "#4A3524",
  "_Trunk": "#6B4A2A",
};

/**
 * Where a pitch/roll keyframe turns each kind, in Scene coords (Z-up),
 * scaled by `scale`. Generated from scene3d/rotation_pivot.py.
 *
 * NOT the authored `position`: that is where the object sits on the floor,
 * which for most kinds is its base. Turning about the base sweeps the whole
 * object around its own footprint instead of turning it on itself -- a crate
 * rotating 360 deg drifted 123 px of silhouette travel, against 8 px here.
 *
 * It is per-kind rather than a computed centroid because the right answer
 * differs per object: a tree sways about its root, a door about its hinge,
 * a rotor about its hub. Kinds are absent when the base IS the pivot.
 */
export const KIND_ROTATION_PIVOT: Readonly<
Partial<Record<PropTypeName | EnvironmentTypeName, readonly [number, number, number]>>
> = {
  "book": [0.0, 0.0, 0.04] as const,
  "box": [0.0, 0.0, 0.4] as const,
  "crate": [0.0, 0.0, 0.45] as const,
  "cup": [0.0, 0.0, 0.07] as const,
  "door": [-0.5, 0.0, 0.0] as const,
  "flat_roof": [0.0, 0.0, 5.2] as const,
  "gable_roof": [0.0, 0.0, 5.5] as const,
  "lantern": [0.0, 0.0, 3.0] as const,
  "pillar": [0.0, 0.0, 2.1] as const,
  "platform": [0.0, 0.0, 0.4] as const,
  "rock": [0.0, 0.0, 0.6] as const,
  "scroll": [0.0, 0.0, 1.0] as const,
  "vase": [0.0, 0.0, 0.3] as const,
  "wall": [0.0, 0.0, 2.5] as const,
  "weapon": [0.0, 0.0, 0.32] as const,
  "window": [0.0, 0.0, 1.8] as const,
};

/**
 * Pose constants, from scene3d/character_pose.py -- the same numbers the
 * Blender converter uses. The walk curve is implemented once per language
 * (the runtimes share nothing), so these are the part that must not drift;
 * `test_character_pose_matches_preview` compares the two implementations'
 * actual output phase by phase, which catches the formulas too.
 *
 * Stride is proportional to the leg, so `stride / (4L)` -- and therefore the
 * leg angle -- is the same for every figure: a child takes shorter steps
 * rather than swinging harder.
 */
export const POSE_CONSTANTS = {
  walkStrideMetres: 1.4,
  referenceLegLengthMetres: 0.925,
  stanceFraction: 0.5,
  walkMaxLegRadians: 0.62,
  defaultLegLengthMetres: 0.85,
  walkArmOverLeg: 0.75,
  walkTorsoRadians: 0.06,
  gestureHeadTiltRadians: -0.26,
  standLegSpreadRadians: 0.05,
  standArmRestRadians: 0.08,
  gestureArmRaiseRadians: 0.9,
  gestureArmOutRadians: 0.35,
  gestureTorsoRadians: 0.12,
  gestureHeadRadians: -0.2,
  sitThighLiftRadians: 1.15,
  sitTorsoRadians: 0.22,
  sitHeadRadians: 0.05,
  talkArmRadians: 0.35,
  talkTorsoRadians: 0.04,
  talkMouthRatio: 0.5,
  mouthClosedRatio: 0.08,
} as const;

/**
 * Held-item grip geometry, from scene3d/held_item_grip.py.
 *
 * A character holding something used to get a prop at a hand offset that
 * was a fixed 0.32 m and 0.72 of the character's height, while the rig hangs
 * the hand at 0.49 of it and places the arm lateral in proportion to height.
 * The two matched at exactly 1.75 m and disagreed for everyone else: a 1.1 m
 * character's weapon sat 60% further outboard than their hand.
 *
 * `armPitchRadians` is the forward rotation the arms need to bring the hand
 * up to the grip. It is height-independent because the shoulder and the target
 * are both proportional to height.
 */
export const HOLD_GRIP = {
  armPitchRadians: 1.352398,
  gripHeightRatio: 0.72,
  kindGripRatio: {"weapon": 0.32},
} as const;

/**
 * The rig's proportions, from scene3d/held_item_grip.py. The held-item
 * geometry above is derived from these, so a change to the rig has to move
 * them together -- which is what a fixed metre constant cannot do.
 */
export const CHARACTER_RIG_FRACTIONS_MIRROR = {
  leg: 0.5,
  torso: 0.3,
  neck: 0.03,
  headRadius: 0.11,
  arm: 0.3,
  armHang: 0.55,
  limbWidth: 0.055,
  torsoWidth: 0.3,
  torsoDepth: 0.16,
  legSpread: 0.075,
  armOutset: 0.6,
  armWidthFactor: 0.8,
  legDepthFactor: 1.2,
  headSeat: 0.85,
} as const;

/**
 * Non-human motion constants, from scene3d/object_motion.py. A door, a wheel
 * and a dropship have no body, so their motion is a delta on the rest pose
 * rather than a set of joint angles -- see objectMotion.ts.
 *
 * These are wall-clock cycles, not distance-driven: a door opens once across
 * its shot and a wheel turns whether or not it is moving.
 */
export const OBJECT_MOTION_CONSTANTS = {
  driveStrideMetres: 12.0,
  flyoverStrideMetres: 60.0,
  doorSwingSeconds: 3.0,
  continuousCycleSeconds: 2.0,
  doorSwingOpenRadians: 1.75,
} as const;

/**
 * The colour a kind with no geometry renders in, chosen so it can never be
 * mistaken for a real surface. Must equal the converter's
 * ``_DEGRADED_ASSET_COLOR`` (#FF2BD1).
 */
export const PLACEHOLDER_ASSET_COLOR = "#FF2BD1";

// Motion preset ids the backend /director-motion endpoint expands (from
// scene3d/director_motion.py), sorted for a deterministic diff. The
// workbench preset tables must match these exactly: a preset the UI
// shows but the backend lacks fails at the gate, and one only the
// backend has is a capability the user never sees.
export const DIRECTOR_CAMERA_MOTION_PRESET_IDS = ["crane_down", "crane_up", "orbit_left", "orbit_right", "pan_left", "pan_right", "pull_out", "push_in"] as const;

export const DIRECTOR_CHARACTER_MOTION_PRESET_IDS = ["approach", "mark_talk", "turn_to", "walk_to"] as const;

/**
 * What each kind measures in metres at `scale = 1`, SceneScript space (Z-up).
 *
 * Mirrored from `apps/web/.../sceneScriptGeometry.tsx` and checked against it
 * by measuring the rendered bounding box. `base` is how far the geometry's
 * underside floats above z = 0 — a non-zero `base` means anything authored
 * on the ground is underneath the object, not beside it.
 */
export interface AssetSceneDimensions {
  /** Extent along x (right), metres. */
  width: number;
  /** Extent along z (up), metres. */
  height: number;
  /** Extent along y (forward), metres. */
  depth: number;
  /** Height of the underside above the ground, metres. */
  base: number;
  shape: string;
  note: string;
}

export const ASSET_SCENE_DIMENSIONS: Record<string, AssetSceneDimensions> = {
  book: { width: 0.34, height: 0.08, depth: 0.26, base: 0, shape: "box", note: "" },
  box: { width: 0.8, height: 0.8, depth: 0.8, base: 0, shape: "box", note: "" },
  chair: { width: 0.5, height: 0.7, depth: 0.515, base: 0.425, shape: "cylinder", note: "`base` is seat height" },
  crate: { width: 0.9, height: 0.9, depth: 0.9, base: 0, shape: "box", note: "" },
  cup: { width: 0.14, height: 0.14, depth: 0.14, base: 0, shape: "cylinder", note: "" },
  door: { width: 1, height: 2.2, depth: 0.15, base: 0, shape: "box", note: "about a person tall" },
  fence: { width: 0.12, height: 0.8, depth: 4.62, base: 0.4, shape: "posts", note: "four posts spread over `depth`" },
  flat_roof: { width: 6.4, height: 0.25, depth: 5.2, base: 5.075, shape: "box", note: "sits on top of a 5 m wall" },
  floor: { width: 15, height: 0.1, depth: 15, base: -0.1, shape: "box", note: "" },
  gable_roof: { width: 8, height: 3, depth: 8, base: 4, shape: "cone", note: "" },
  ground: { width: 15, height: 0.1, depth: 15, base: -0.1, shape: "box", note: "site plate; scale 2 gives a 30 m square" },
  lantern: { width: 0.3, height: 0.4, depth: 0.3, base: 2.6, shape: "cylinder", note: "HANGS: `base` is its hook height" },
  lowpoly_human: { width: 0.7, height: 1.8, depth: 0.7, base: 0, shape: "segments", note: "seven segments; `appearance.height` sets the real size" },
  pillar: { width: 0.6, height: 4.2, depth: 0.6, base: 0, shape: "cylinder", note: "scale 1 is 4.2 m — already a tall column" },
  platform: { width: 5, height: 0.4, depth: 5, base: 0.2, shape: "box", note: "FLOATS: the slab's underside is `base` above the ground" },
  rect_table: { width: 1.5, height: 0.05, depth: 0.9, base: 0.725, shape: "box", note: "a tabletop on legs; `base` is leg height" },
  rock: { width: 2.52, height: 1.44, depth: 1.98, base: -0.12, shape: "icosahedron", note: "sits slightly buried" },
  round_table: { width: 1.2, height: 0.775, depth: 1.2, base: 0, shape: "cylinder", note: "" },
  scroll: { width: 0.24, height: 0.9, depth: 0.24, base: 0.55, shape: "cylinder", note: "a rolled tube on a stand" },
  stairs: { width: 2.4, height: 1, depth: 4.5, base: 0.1, shape: "steps", note: "four treads climbing along depth" },
  stool: { width: 0.56, height: 0.53, depth: 0.56, base: 0, shape: "cylinder", note: "" },
  tree: { width: 3.4, height: 5.1, depth: 3.4, base: 0, shape: "icosahedron", note: "" },
  vase: { width: 0.28, height: 0.6, depth: 0.28, base: 0, shape: "cylinder", note: "" },
  wall: { width: 6, height: 5, depth: 0.3, base: 0, shape: "box", note: "thin in depth: a WALL, not a block" },
  weapon: { width: 0.06, height: 1.37, depth: 0.05, base: 0.18, shape: "group", note: "a blade; scale 1.2 is a rifle" },
  window: { width: 1.4, height: 1.6, depth: 0.12, base: 1, shape: "box", note: "sill at `base` = 1 m" },
};

/** The size a SceneScript is implicitly written against, in metres. */
export const REFERENCE_PERSON_HEIGHT = 1.75;
