/*
 * Generated by app.cli.generate_scene_script_preview_contract.
 * Do not edit manually -- run
 *   python -m app.cli.generate_scene_script_preview_contract
 * Source of truth: app/schemas/scene_script.py + scene3d/blender_converter.py
 *
 * apps/web tests that every preview kind has geometry import these, so a
 * kind added to the schema fails the frontend build instead of silently
 * rendering as a grey placeholder box.
 */

// Kinds the backend schema declares, so the preview can assert it covers all of them.
export const PROP_TYPES = ["round_table", "rect_table", "chair", "stool", "lantern", "box", "crate", "vase", "weapon", "scroll", "book", "cup"] as const;

export const ENVIRONMENT_TYPES = ["wall", "pillar", "floor", "gable_roof", "flat_roof", "door", "window", "stairs", "platform", "tree", "rock", "fence", "ground"] as const;

export type PropTypeName = (typeof PROP_TYPES)[number];
export type EnvironmentTypeName = (typeof ENVIRONMENT_TYPES)[number];

/**
 * Colour each declared kind renders in. Mirrors the converter's
 * ``_ASSET_COLORS`` so the browser preview and the Blender frames agree,
 * and so the placeholder below is the one colour no real asset uses.
 */
export const SCENE_SCRIPT_ASSET_COLORS: Readonly<Record<string, string>> = {
  book: "#8B3A3A",
  box: "#B08D57",
  chair: "#7A5230",
  crate: "#8C6239",
  cup: "#D9D8D0",
  door: "#5C3A21",
  fence: "#7E6242",
  flat_roof: "#5A5A62",
  floor: "#7A6748",
  gable_roof: "#8C4A38",
  ground: "#6E7A45",
  lantern: "#E8B84B",
  pillar: "#C4B79B",
  platform: "#8A7554",
  rect_table: "#A9743F",
  rock: "#82807A",
  round_table: "#8B5A2B",
  scroll: "#E8DCC0",
  stairs: "#96795A",
  stool: "#9C6B3F",
  tree: "#6B4A2A",
  vase: "#C86B8A",
  wall: "#CDBFA3",
  weapon: "#9AA3AD",
  window: "#A8CBD8",
};

/**
 * Per-part overrides for multi-part assets, keyed by the part-name
 * suffix the converter's builders assign. Without this a tree renders
 * as one brown mass instead of a trunk under a canopy, so the browser
 * would disagree with the Blender frames about what a tree is.
 */
export const SCENE_SCRIPT_PART_COLOR_OVERRIDES: Readonly<
Record<string, string>
> = {
  "_Blade": "#9AA3AD",
  "_Canopy": "#4E7A3A",
  "_Grip": "#4A3524",
  "_Trunk": "#6B4A2A",
};

/**
 * The colour a kind with no geometry renders in, chosen so it can never be
 * mistaken for a real surface. Must equal the converter's
 * ``_DEGRADED_ASSET_COLOR`` (#FF2BD1).
 */
export const PLACEHOLDER_ASSET_COLOR = "#FF2BD1";
