"""Serialize subtitle-track timeline clips to SRT and ASS (ADR 0007 Phase 3.3).

Pure functions: clips in, document text out. The writer powers both the
sidecar download endpoint and the burn-in step of the export renderer, so
SRT and ASS must agree on cue selection, ordering and timing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from app.schemas.timeline import (
    TimelineClipV1,
    TimelineSubtitlePositionV1,
    TimelineSubtitleStyleV1,
)

# ASS is authored against a 1080p canvas; libass scales styles to the real
# output resolution automatically.
ASS_PLAY_RES_X = 1920
ASS_PLAY_RES_Y = 1080

DEFAULT_FONT_FAMILY = "Arial"
DEFAULT_FONT_SIZE = 52
DEFAULT_PRIMARY_COLOR = "#FFFFFF"
DEFAULT_OUTLINE_COLOR = "#101010"
DEFAULT_POSITION: TimelineSubtitlePositionV1 = "bottom"
DEFAULT_OUTLINE_WIDTH = 3
DEFAULT_MARGIN_VERTICAL = 60

# ASS numpad alignment (horizontally centred): 2 bottom, 5 middle, 8 top.
_ASS_ALIGNMENT: dict[str, int] = {"bottom": 2, "middle": 5, "top": 8}


@dataclass(frozen=True, slots=True)
class SubtitleCue:
    """One renderable subtitle cue derived from a timeline clip."""

    text: str
    start_seconds: float
    end_seconds: float
    style: TimelineSubtitleStyleV1 | None = None


def collect_subtitle_cues(
    clips: Sequence[TimelineClipV1],
) -> tuple[SubtitleCue, ...]:
    """Extract ordered, non-empty cues from subtitle clips.

    Clips without text, with non-positive duration or reversed timing are
    skipped so neither serializer can emit invalid cues.
    """
    cues: list[SubtitleCue] = []
    for clip in clips:
        text = (clip.subtitle_text or "").strip()
        if not text:
            continue
        start = max(clip.start_time, 0.0)
        end = clip.start_time + clip.duration
        if end <= start:
            continue
        cues.append(
            SubtitleCue(
                text=text,
                start_seconds=start,
                end_seconds=end,
                style=clip.subtitle_style,
            )
        )
    cues.sort(key=lambda cue: (cue.start_seconds, cue.end_seconds))
    return tuple(cues)


def clips_to_srt(clips: Sequence[TimelineClipV1]) -> str:
    """Render subtitle clips as an SRT 1.0 document (UTF-8)."""
    cues = collect_subtitle_cues(clips)
    blocks: list[str] = []
    for index, cue in enumerate(cues, start=1):
        blocks.append(
            f"{index}\n"
            f"{_format_srt_time(cue.start_seconds)} --> "
            f"{_format_srt_time(cue.end_seconds)}\n"
            f"{cue.text}\n"
        )
    return "\n".join(blocks)


def clips_to_ass(
    clips: Sequence[TimelineClipV1],
    *,
    play_res_x: int = ASS_PLAY_RES_X,
    play_res_y: int = ASS_PLAY_RES_Y,
) -> str:
    """Render subtitle clips as an ASS v4+ document with one style per cue."""
    return cues_to_ass(
        collect_subtitle_cues(clips),
        play_res_x=play_res_x,
        play_res_y=play_res_y,
    )


def cues_to_ass(
    cues: Sequence[SubtitleCue],
    *,
    play_res_x: int = ASS_PLAY_RES_X,
    play_res_y: int = ASS_PLAY_RES_Y,
) -> str:
    """Render pre-collected cues as an ASS v4+ document.

    Cues are expected to already be filtered and ordered; the export renderer
    builds them directly from EditingSubtitleEntryV2 instead of timeline clips.
    """
    styled_indexes = [
        index
        for index, cue in enumerate(cues, start=1)
        if cue.style is not None and not _style_is_empty(cue.style)
    ]

    lines: list[str] = [
        "[Script Info]",
        "; Generated by myAdcraft timeline subtitle writer",
        "ScriptType: v4.00+",
        f"PlayResX: {play_res_x}",
        f"PlayResY: {play_res_y}",
        "WrapStyle: 2",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        _ASS_STYLE_FORMAT,
        _default_ass_style_line(),
    ]
    for index in styled_indexes:
        cue = cues[index - 1]
        assert cue.style is not None
        lines.append(_ass_style_line(f"Subtitle{index}", cue.style))

    lines.extend(
        [
            "",
            "[Events]",
            _ASS_EVENT_FORMAT,
        ]
    )
    for index, cue in enumerate(cues, start=1):
        style_name = (
            f"Subtitle{index}"
            if cue.style is not None and not _style_is_empty(cue.style)
            else "Default"
        )
        lines.append(
            "Dialogue: 0,"
            f"{_format_ass_time(cue.start_seconds)},"
            f"{_format_ass_time(cue.end_seconds)},"
            f"{style_name},,0,0,0,,{_sanitize_ass_text(cue.text)}"
        )

    return "\n".join(lines) + "\n"


_ASS_STYLE_FORMAT = (
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
    "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
    "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
    "Alignment, MarginL, MarginR, MarginV, Encoding"
)

_ASS_EVENT_FORMAT = (
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
    "Effect, Text"
)


def _style_is_empty(style: TimelineSubtitleStyleV1) -> bool:
    return all(value is None for value in style.model_dump().values())


def _default_ass_style_line() -> str:
    return _ass_style_line(
        "Default",
        TimelineSubtitleStyleV1(
            font_family=DEFAULT_FONT_FAMILY,
            font_size=DEFAULT_FONT_SIZE,
            primary_color=DEFAULT_PRIMARY_COLOR,
            outline_color=DEFAULT_OUTLINE_COLOR,
            position=DEFAULT_POSITION,
            bold=False,
            italic=False,
        ),
    )


def _ass_style_line(name: str, style: TimelineSubtitleStyleV1) -> str:
    position = style.position or DEFAULT_POSITION
    margin_vertical = (
        DEFAULT_MARGIN_VERTICAL if position in {"bottom", "top"} else 0
    )
    return (
        f"Style: {name},"
        f"{style.font_family or DEFAULT_FONT_FAMILY},"
        f"{style.font_size or DEFAULT_FONT_SIZE},"
        f"{_ass_color(style.primary_color, DEFAULT_PRIMARY_COLOR)},"
        f"{_ass_color(style.primary_color, DEFAULT_PRIMARY_COLOR)},"
        f"{_ass_color(style.outline_color, DEFAULT_OUTLINE_COLOR)},"
        "&H80000000,"  # BackColour: semi-transparent black
        f"{-1 if style.bold else 0},"
        f"{-1 if style.italic else 0},"
        "0,0,100,100,0,0,1,"
        f"{DEFAULT_OUTLINE_WIDTH},0,"
        f"{_ASS_ALIGNMENT[position]},"
        f"40,40,{margin_vertical},1"
    )


def _ass_color(hex_color: str | None, fallback: str) -> str:
    """Convert #RRGGBB / #RGB to the ASS '&HAABBGGRR' word (opaque)."""
    raw = (hex_color or fallback).lstrip("#")
    if len(raw) == 3:
        raw = "".join(character * 2 for character in raw)
    red, green, blue = raw[0:2], raw[2:4], raw[4:6]
    return f"&H00{blue}{green}{red}".upper()


def _sanitize_ass_text(text: str) -> str:
    r"""Escape text for an ASS Dialogue line.

    Line breaks become ``\N``; bare braces would be parsed as override tags,
    so they are substituted (ASS has no brace escape sequence).
    """
    return (
        text.replace("{", "(")
        .replace("}", ")")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
        .replace("\n", r"\N")
    )


def _format_srt_time(seconds: float) -> str:
    milliseconds = round(max(seconds, 0.0) * 1000)
    hours, remainder = divmod(milliseconds, 3_600_000)
    minutes, remainder = divmod(remainder, 60_000)
    whole_seconds, milliseconds = divmod(remainder, 1000)
    return f"{hours:02}:{minutes:02}:{whole_seconds:02},{milliseconds:03}"


def _format_ass_time(seconds: float) -> str:
    centiseconds = round(max(seconds, 0.0) * 100)
    hours, remainder = divmod(centiseconds, 360_000)
    minutes, remainder = divmod(remainder, 6000)
    whole_seconds, centiseconds = divmod(remainder, 100)
    return f"{hours}:{minutes:02}:{whole_seconds:02}.{centiseconds:02}"
