"""Blender headless renderer service.

Manages Blender subprocess invocation for rendering SceneScript animations.
Handles timeout, cleanup, and capability fingerprinting.

Blender is invoked as: blender --background --python <script.py>
The script is generated by blender_converter.py.

See: docs/3d-previs/blender-integration-guide.md
"""

from __future__ import annotations

import os
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

from app.schemas.scene_script import SceneScriptRoot
from app.services.scene3d.blender_converter import (
    degraded_asset_ids,
    scene_script_to_blender,
)


@dataclass
class RenderResult:
    """Result of a Blender render job."""

    success: bool
    output_dir: str | None = None
    frame_count: int = 0
    error: str | None = None
    duration_seconds: float = 0.0
    blender_version: str | None = None
    # Asset types that had no real geometry and were rendered as placeholder
    # boxes.  ADR 0005 requires previs control level to be "queryable, never
    # silent", so a silently-degraded shot must be reportable rather than
    # indistinguishable from a faithful one.
    degraded_assets: tuple[str, ...] = ()
    # Which frames were actually rendered.  "keyframes" means the draft pass
    # (5 per shot); "animation" means every frame.  A consumer that assumes a
    # continuous sequence must not treat a draft as one.
    rendered_frames: str = "animation"


@dataclass
class BlenderCapability:
    """Blender availability fingerprint."""

    state: str = "unsupported"  # ready | degraded | unsupported
    version: str | None = None
    executable: str | None = None
    error: str | None = None


_cached_capability: BlenderCapability | None = None


def get_blender_capability(executable: str | None = None) -> BlenderCapability:
    """Probe Blender availability. Cached after first call.

    Args:
        executable: Path to blender executable. Defaults to BLENDER_EXECUTABLE
                    env var or 'blender' on PATH.

    Returns:
        BlenderCapability with state, version, and error info.
    """
    global _cached_capability
    # When an explicit executable is passed, bypass cache to honor the override.
    if executable is None and _cached_capability is not None:
        return _cached_capability

    exe = executable or os.environ.get("BLENDER_EXECUTABLE", "blender")
    cap = BlenderCapability(executable=exe)

    try:
        result = subprocess.run(
            [exe, "--version"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            # Parse version from output like "Blender 5.2.1 (hash 9e2066aef7ef built 2026-08-25)"
            first_line = result.stdout.strip().split("\n")[0] if result.stdout else ""
            cap.version = first_line
            cap.state = "ready"
        else:
            cap.state = "unsupported"
            cap.error = f"blender --version returned {result.returncode}: {result.stderr[:200]}"
    except FileNotFoundError:
        cap.state = "unsupported"
        cap.error = f"Blender executable not found: {exe}"
    except subprocess.TimeoutExpired:
        cap.state = "degraded"
        cap.error = "Blender version probe timed out"
    except Exception as exc:
        cap.state = "unsupported"
        cap.error = f"Blender probe failed: {exc}"

    _cached_capability = cap
    return cap


def reset_capability_cache() -> None:
    """Reset the cached capability (for testing)."""
    global _cached_capability
    _cached_capability = None


def render_scene_script(
    scene_script: SceneScriptRoot,
    output_dir: str,
    executable: str | None = None,
    timeout_seconds: int = 600,
    include_control_passes: bool = False,
    keyframes_only: bool = False,
) -> RenderResult:
    """Render a SceneScript to PNG frames using Blender headless.

    Args:
        scene_script: Validated SceneScript root.
        output_dir: Directory to write rendered PNG frames.
        executable: Blender executable path (optional).
        timeout_seconds: Maximum render time per job.
        include_control_passes: When True, the generated script also renders
            geometric control passes (depth/normal/flow) into sibling
            subdirectories of ``output_dir`` (ADR 0005 §4).
        keyframes_only: When True, render only the keyframe frames (5 per shot)
            as stills instead of the whole animation.  Same scene, same images
            at those instants, roughly a tenth of the work.
    """
    start_time = time.time()
    exe = executable or os.environ.get("BLENDER_EXECUTABLE", "blender")
    degraded = degraded_asset_ids(scene_script)
    rendered_frames = "keyframes" if keyframes_only else "animation"

    # Check capability
    cap = get_blender_capability(exe)
    if cap.state == "unsupported":
        return RenderResult(
            success=False,
            error=f"Blender not available: {cap.error}",
            duration_seconds=time.time() - start_time,
            degraded_assets=degraded,
            rendered_frames=rendered_frames,
        )

    # Ensure output directory exists
    output_dir = os.path.abspath(output_dir)
    os.makedirs(output_dir, exist_ok=True)

    # Generate Blender script.  The path must be absolute: Blender resolves a
    # relative render filepath against the current drive root on Windows
    # (e.g. ``data/...`` becomes ``C:\data\...``), which silently renders to
    # the wrong location when cwd != drive root.
    script_content = scene_script_to_blender(
        scene_script,
        output_dir,
        include_control_passes=include_control_passes,
        keyframes_only=keyframes_only,
    )

    # Write script to temp file
    script_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        ) as f:
            f.write(script_content)
            script_path = f.name

        # Run Blender
        cmd = [exe, "--background", "--python", script_path]
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
                cwd=output_dir,
            )
        except subprocess.TimeoutExpired:
            # Report how far the render actually got: "timed out with 0 frames"
            # points at a stuck scene, while "timed out with 40/72 frames"
            # means the timeout budget is simply too small for this script.
            rendered = len(list(Path(output_dir).glob("frame_*.png")))
            return RenderResult(
                success=False,
                error=(
                    f"Blender render timed out after {timeout_seconds}s "
                    f"with {rendered} frame(s) written."
                ),
                duration_seconds=time.time() - start_time,
                blender_version=cap.version,
                degraded_assets=degraded,
                rendered_frames=rendered_frames,
            )

        # Count rendered frames
        frame_files = list(Path(output_dir).glob("frame_*.png"))
        frame_count = len(frame_files)

        # Blender reports ``returncode == 0`` even when the embedded script
        # raised: the traceback goes to stderr *after* "Blender quit". Without
        # this check a crashed control pass (or any post-render step) looks like
        # a clean success and the caller silently receives a degraded shot.
        stderr_text = result.stderr or ""
        script_failed = "Traceback (most recent call last)" in stderr_text

        if (result.returncode != 0 or script_failed) and frame_count == 0:
            error_tail = (stderr_text or result.stdout or "")[-500:]
            if result.returncode != 0:
                error = f"Blender exited with code {result.returncode}: {error_tail}"
            else:
                error = f"Blender script raised an exception: {error_tail}"
            return RenderResult(
                success=False,
                error=error,
                output_dir=output_dir,
                frame_count=frame_count,
                duration_seconds=time.time() - start_time,
                blender_version=cap.version,
                degraded_assets=degraded,
                rendered_frames=rendered_frames,
            )

        if script_failed:
            # Frames exist, so the color pass is usable, but a post-render
            # stage (e.g. the geometric control passes) did not finish.
            # Surface it in the error text; callers keep the frames and the
            # message keeps the degradation queryable (ADR 0005).
            error_tail = (stderr_text or "")[-500:]
            return RenderResult(
                success=True,
                output_dir=output_dir,
                frame_count=frame_count,
                error=(
                    "Color pass rendered, but a post-render stage raised an "
                    f"exception: {error_tail}"
                ),
                duration_seconds=time.time() - start_time,
                blender_version=cap.version,
                degraded_assets=degraded,
                rendered_frames=rendered_frames,
            )

        return RenderResult(
            success=True,
            output_dir=output_dir,
            frame_count=frame_count,
            duration_seconds=time.time() - start_time,
            blender_version=cap.version,
            degraded_assets=degraded,
            rendered_frames=rendered_frames,
        )

    finally:
        # Clean up temp script
        if script_path and os.path.exists(script_path):
            try:
                os.unlink(script_path)
            except OSError:
                pass
